# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e13c7c17ddbd3e8d5865948e21b552c9"
name = "factoryengine"
application_url = "https://api.eagledtfsupply.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
scopes = "read_products,write_products,read_orders,write_orders,read_customers,write_customers,read_themes,write_themes,read_content,write_content,read_inventory,write_inventory,read_shipping,write_shipping,write_price_rules,write_discounts"

[auth]
redirect_urls = [
  "https://api.eagledtfsupply.com/api/v1/auth/shopify/callback",
  "https://api.eagledtfsupply.com/api/auth/shopify/callback",
  "https://app.eagledtfsupply.com/api/auth/callback"
]
